better update script

diff --git a/dotfiles/sd/nixos/update b/dotfiles/sd/nixos/update
--- a/dotfiles/sd/nixos/update
+++ b/dotfiles/sd/nixos/update
@@ -1,15 +1,43 @@
 #!/usr/bin/env bash
-fwupdmgr refresh
-fwupdmgr get-updates
-fwupdmgr update
+
+
 pushd $FLAKE || exit
-nix flake update
-nixos-rebuild --flake $FLAKE build |&nom
+
+LAST_UPDATED=$(nix flake metadata | grep "Last modified" | awk '{print $3}')
+
+if [[ $LAST_UPDATED != $(date +%Y-%m-%d) ]]; then
+
+    fwupdmgr refresh
+    fwupdmgr get-updates
+    fwupdmgr update
+
+    nix flake update
+else
+    echo "Flake inputs already updated today. Skipping re-download."
+fi
+
+
+nixos-rebuild build --flake ./ |&nom
+
+if [[ "${PIPESTATUS[0]}" != "0"  ]]; then
+    echo "Build failed!"
+    exit 1
+fi
+
 nvd diff /run/current-system result
+
 read  -n 1 -p "any key to continue or Ctrl-c to aboard" input
+
 if [[ "$1" == "gc" ]]; then
     echo "collecting garbage"
     sudo nix-collect-garbage -d
 fi
+
 sudo nixos-rebuild boot --flake $FLAKE |& nom
+
+# check if result folder symlink exists
+if [[ -L result ]]; then
+    rm ./result
+fi
+
 popd || exit
